# Generated by Django 2.2.2 on 2019-07-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
