# Generated by Django 2.2.2 on 2019-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190715_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateTimeField(auto_now=True)),
                ('tableno', models.IntegerField(unique_for_date='dt')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
