# Generated by Django 2.2.2 on 2019-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190718_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='dt',
            field=models.DateTimeField(),
        ),
    ]
