# Generated by Django 2.2.2 on 2019-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190718_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='tableno',
            field=models.IntegerField(error_messages={'unique_for_date': 'kol'}, unique_for_date='dt'),
        ),
    ]
