# Generated by Django 2.2.2 on 2019-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190718_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='dt',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tableno',
            field=models.IntegerField(error_messages={'unique_for_date': 'This table is not available at this moment'}, unique_for_date='dt'),
        ),
    ]
