# Generated by Django 2.2.2 on 2019-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190718_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='dt',
            field=models.DateField(),
        ),
    ]
