# Generated by Django 2.2.2 on 2019-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190718_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='et',
            field=models.CharField(default='<django.db.models.fields.DateTimeField>1', max_length=200),
        ),
    ]
