# Generated by Django 2.2.2 on 2019-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190719_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='dt',
            field=models.DateField(),
        ),
    ]
