# Generated by Django 2.2.2 on 2019-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190719_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='tt',
            field=models.CharField(max_length=30),
        ),
    ]
